title: "Affiliates"
email: danielcarvajalpelicano@gmail.com
timezone: UTC
baseurl: "/affiliates"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'Affiliates'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Daniel
    display_name: dacape
    avatar: 'assets/images/sal.png'
    email: danielcarvajalpelicano@gmail.com
    web: https://www.dacape.dev
    twitter: https://twitter.com/dacape.dev
    description: ""
  
# Social
social:
  twitter: https://twitter.com/dacape.dev

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives